/** Sample content, used only until a Sanity project is connected.
 *  Every restaurant here is invented — the point is to show what a full site
 *  looks like, not to review anyone. Once SANITY_PROJECT_ID is set this file
 *  is ignored entirely. */

import type { Post, Salad, Settings } from './types';

export const sampleSalads: Salad[] = [
  {
    id: 'sample-1',
    restaurant: 'ביסטרו רוזמרין',
    slug: 'bistro-rosemary',
    city: 'תל אביב',
    address: 'שדרות רוטשילד 42',
    lat: 32.0645,
    lng: 34.7748,
    score: 9,
    subScores: { dressing: 10, lettuce: 9, croutons: 8, parmesan: 9, protein: 8, value: 7 },
    price: 74,
    visitedAt: '2026-06-14',
    verdict: 'הרוטב הכי מדויק שפגשתי השנה. אנשובי אמיתי, בלי התנצלויות.',
    bodyHtml: `<p>יש רגע שבו את טועמת רוטב קיסר ומבינה שמישהו במטבח באמת אוהב את מה שהוא עושה. זה היה הרגע הזה. חמיצות מדודה, שום שנוכח אבל לא צועק, ואנשובי שמרגישים בו — לא כרמז, כעובדה.</p><p>החסה קרה ופריכה, חתוכה בגודל שאפשר לאכול בלי סכין. הקרוטונים ביתיים, קצת שמן זית מדי לטעמי, אבל אני סולחת. הפרמזן מגורד גס, וזה תמיד הבחירה הנכונה.</p><blockquote>אם היו מגישים לי רק את הרוטב עם כף, הייתי מזמינה שוב.</blockquote><p>המחיר גבוה, וזה מה שמנע ממנו את העשר.</p>`,
    photos: [],
    tags: ['אנשובי', 'קרוטונים ביתיים', 'ארוחת צהריים'],
    wouldReturn: true,
    featured: true,
  },
  {
    id: 'sample-2',
    restaurant: 'מזנון הצדף',
    slug: 'miznon-hatsedef',
    city: 'יפו',
    address: 'נמל יפו',
    lat: 32.0525,
    lng: 34.7519,
    score: 8.5,
    subScores: { dressing: 8, lettuce: 9, croutons: 9, parmesan: 7, protein: 9 },
    price: 68,
    visitedAt: '2026-05-30',
    verdict: 'הקרוטונים פריכים בצורה שגורמת לשולחן שלידך להסתכל.',
    bodyHtml: `<p>ישבתי מול הים, וזה כנראה הוסיף חצי נקודה. אבל גם בלי הים — הסלט הזה יודע מה הוא רוצה להיות.</p><p>הדג שהוסיפו במקום עוף הפתיע אותי לטובה. הרוטב קצת עדין מדי, ואני אוהבת שהוא נושך.</p>`,
    photos: [],
    tags: ['נוף לים', 'דגים', 'סוף שבוע'],
    wouldReturn: true,
  },
  {
    id: 'sample-3',
    restaurant: 'קפה לואיז',
    slug: 'cafe-louise',
    city: 'תל אביב',
    address: 'שבזי 18, נווה צדק',
    lat: 32.0616,
    lng: 34.7639,
    score: 7.5,
    subScores: { dressing: 7, lettuce: 8, croutons: 6, parmesan: 8, value: 8 },
    price: 56,
    visitedAt: '2026-05-11',
    verdict: 'סלט הגון של שכונה טובה. לא מרגש, אבל אף פעם לא מאכזב.',
    bodyHtml: `<p>יש מקומות שאת חוזרת אליהם בגלל הכיסא ליד החלון. זה אחד מהם. הסלט טוב, המנה גדולה, והמחיר הוגן.</p><p>הקרוטונים מהשקית. אני יודעת, גם הם יודעים, וכולנו ממשיכים בחיינו.</p>`,
    photos: [],
    tags: ['שכונתי', 'מחיר הוגן'],
    wouldReturn: true,
  },
  {
    id: 'sample-4',
    restaurant: 'טרצה',
    slug: 'terza',
    city: 'ירושלים',
    address: 'מחנה יהודה',
    lat: 31.7854,
    lng: 35.2124,
    score: 8,
    subScores: { dressing: 9, lettuce: 7, croutons: 8, parmesan: 8, protein: 7, value: 8 },
    price: 62,
    visitedAt: '2026-04-22',
    verdict: 'רוטב אמיץ, חסה עייפה. יחד הם עדיין מסתדרים.',
    bodyHtml: `<p>הגעתי בשעה שאף אחד לא מגיע, וקיבלתי סלט שהורכב באהבה בשביל אדם אחד. הרוטב חזק, לימוני, עם חרדל שמרגישים.</p><p>החסה, לעומת זאת, כבר ראתה ימים טובים יותר. חבל.</p>`,
    photos: [],
    tags: ['שוק', 'רוטב חזק'],
    wouldReturn: true,
  },
  {
    id: 'sample-5',
    restaurant: 'הפינה של אמיליה',
    slug: 'emilia-corner',
    city: 'רמת גן',
    address: 'ביאליק 31',
    lat: 32.0823,
    lng: 34.8103,
    score: 6,
    subScores: { dressing: 5, lettuce: 7, croutons: 7, parmesan: 4, value: 6 },
    price: 52,
    visitedAt: '2026-03-08',
    verdict: 'פרמזן שהוא בעצם גבינה צהובה. נו, באמת.',
    bodyHtml: `<p>אני מוכנה לסלוח על הרבה דברים, אבל לא על פרמזן מזויף. הכל השאר היה סביר לגמרי, ודווקא בגלל זה זה מעצבן.</p>`,
    photos: [],
    tags: ['אכזבה קטנה'],
    wouldReturn: false,
  },
  {
    id: 'sample-6',
    restaurant: 'סלט וחצי',
    slug: 'salat-vahetsi',
    city: 'הרצליה',
    address: 'מדינת היהודים 60',
    lat: 32.1624,
    lng: 34.8065,
    score: 4.5,
    subScores: { dressing: 3, lettuce: 6, croutons: 5, parmesan: 4, value: 4 },
    price: 64,
    visitedAt: '2026-02-19',
    verdict: 'מיונז שמתחזה לרוטב קיסר. התחזות לא משכנעת.',
    bodyHtml: `<p>לא כל דבר לבן שנמרח על חסה הוא רוטב קיסר. זה נכתב מתוך אהבה, ומתוך רצון שמישהו שם יקרא ויתקן.</p>`,
    photos: [],
    tags: ['לא שוב'],
    wouldReturn: false,
  },
];

export const samplePosts: Post[] = [
  {
    id: 'sample-post-1',
    title: 'למה דווקא קיסר',
    slug: 'why-caesar',
    publishedAt: '2026-06-02',
    excerpt: 'כי סלט קיסר הוא מבחן. חמישה מרכיבים, שום מקום להתחבא.',
    bodyHtml: `<p>אנשים שואלים אותי למה אני מזמינה תמיד את אותו הדבר. התשובה היא שסלט קיסר הוא לא מנה, הוא בדיקה.</p><p>יש בו חמישה מרכיבים. חסה, רוטב, קרוטונים, פרמזן, ומשהו שמוסיפים כדי להצדיק את המחיר. אין רוטב חריף שיכסה, אין רוטב מתוק שיסיח את הדעת. או שהמטבח יודע מה הוא עושה, או שלא.</p><h2>מה אני בעצם בודקת</h2><p>קודם כל את הרוטב. אחר כך את הטמפרטורה של החסה — סלט קיסר פושר הוא סלט קיסר מובס. ורק בסוף את הקרוטונים, שהם החלק שהכי קל לזייף בו ושהכי קל גם לעשות נכון.</p><p>וזהו. זה כל הסוד.</p>`,
    tags: ['מחשבות', 'אוכל'],
    readingMinutes: 2,
  },
  {
    id: 'sample-post-2',
    title: 'בוקר אחד בשוק',
    slug: 'morning-at-the-market',
    publishedAt: '2026-05-18',
    excerpt: 'לא כתבתי על אוכל. כתבתי על אישה שמכרה לי עגבניות.',
    bodyHtml: `<p>היא שקלה את העגבניות פעמיים, לא בגלל שהמאזניים טעו אלא בגלל שהיא רצתה שאני אראה.</p><p>יש אנשים שעושים את העבודה שלהם כאילו מישהו מסתכל תמיד. אני חושבת שזה הדבר הכי קרוב לאמונה שראיתי השבוע.</p>`,
    tags: ['מחשבות'],
    readingMinutes: 1,
  },
  {
    id: 'sample-post-3',
    title: 'על זה שכולם מפחדים מאנשובי',
    slug: 'anchovy',
    publishedAt: '2026-04-05',
    excerpt: 'הדג הקטן הזה הוא ההבדל בין רוטב לבין מים עם שמנת.',
    bodyHtml: `<p>כשאני שואלת מלצרים אם יש אנשובי ברוטב, רובם עונים "לא, לא, אל תדאגי". הם חושבים שהם מרגיעים אותי.</p><p>אני רוצה להגיד להם: זה בדיוק מה שחיפשתי.</p>`,
    tags: ['אוכל', 'דעות'],
    readingMinutes: 1,
  },
];

export const sampleSettings: Settings = {
  title: 'הקיסרית',
  tagline: 'מדריך אישי לסלטי קיסר, ולעוד כמה דברים שעוברים לי בראש',
  heroText: 'אני אוכלת סלט קיסר בכל מקום שאני מגיעה אליו, ומדרגת. בין סלט לסלט אני גם כותבת.',
  aboutTitle: 'קצת עליי',
  aboutHtml: `<p>שלום, אני כאן כדי לדרג סלטי קיסר. התחלתי כי חבר אמר לי שאין הבדל אמיתי בין אחד לשני, והמשכתי כי התברר שהוא טעה מאוד.</p><p>בין דירוג לדירוג אני כותבת על דברים אחרים לגמרי. זה החלק שאני הכי אוהבת.</p>`,
  scaleNote: 'הדירוג הוא מ־1 עד 10, ואין בו שום דבר מדעי. זה הטעם שלי.',
};
